### PR TITLE
Stratagems, with Allegiance as necessitated by restrictions.

### LINKED ISSUE #35: Stratagems
* [x] Stratagem Points and constraints based on Battle Rating
* [x] Stratagems and Rules
* [x] Outlflank Stratagem Point Calculations
* [ ] Underdog Stratagem Point Bonuses

I'm not sure quite how to implement this last one; there may be a way to do it WRG to different sorts of point totals (Force vs Roster) etc? Implementation suggestions welcome.

### PR DESCRIPTION
**Pull request by capitaladot**
Closes #35

### CODE REVIEW

**Comment by morvael** [comment]
Legio-specific strategems show cost as text in parentheses but do not really cost any Stratagem Points.

I assume you have tied SP limit to roster points limit? I have configured roster to hard limit of 1000 pts and 3 SP, but was still warned that I have "spent 1 Stratagem Points too much from Stratagem (maximum 2 Stratagem Points)".

**Comment by capitaladot** [comment]
Thanks @morvael, I have hand edited those Legio specific Stratagem points out of the titles and into the new Stratagem Point cost. 

Likewise, the breakpoint to get 3 Stratagems is actually 1250. Please see p84 in AT2018.

Please have another look?

**Comment by morvael** [comment]
Works fine for me. You did a great job!

I'm still not a fan of how the data file works in first place (though some limitations come from BattleScribe itself).

**Comment by morvael** [comment]
@Xemit64 will you review this please, and merge if satisfied?

**Pull request merged**
