### PR TITLE
Update Household.cat

### PR DESCRIPTION
**Pull request by Prioress**
Sorry, I am new to this. I have been trying to fix a bug that prevents users from selecting lance banners in Household Rosters. I probably broke other things too, but I got that to work. Mind checking over my work?

### CODE REVIEW

**Comment by zopha** [comment]
I @Deviltree was going to work on this, I'm not sure if he's made any progress but I'll try to have give it a look over. Hopefully it's all good and get it merged, will be good to give the knights some love.

**Comment by Prioress** [comment]
Hey! I hope I didn’t break anything. I mostly just corrected the errors in
the Household file and linked the banners so they would be selectable.
Hopefully nothing broke.

**Comment by zopha** [comment]
Getting an error when I try to build a roster :(

Does it work for you?

image

Might have found the issue but I'm not sure why, 

image

The XML line is present at the begining of the file where it should be but also appears in a rule description. Looking at it again and it looks like the first 24 lines of code have been duplicated, the categoryEntries start again at line 26.

notepad++_92DCRAN2S0

You can fix it by using a text editor to remove lines 2 to 23 inclusive and save it as a new commit. The lines highlighted here - 

image

sorry, lots of large images.

What did you use to edit the file?

**Comment by Prioress** [comment]
I used the Battlescribe Data Editor ^^;. I’ll get to work on it as soon as
I can!

**Comment by zopha** [comment]
It must have corrupted it in someway, can you open the file on your system? I downloaded your version from github and BS crashes when it tries to load it.

**Comment by Prioress** [comment]
Yeah I can, I basically always test with Battlescribe open to check if it
works. I probably messed something up though.

**Comment by MoDLegion** [comment]
As @zopha mentioned, once the duplicated code in lines 1 through 23 is removed the file loads. While your change does work when this is done, I think you have misunderstood how a Household roster is created (see the comments on #195). This change would indeed break a lot of things because what you have basically done is duplicated all Lance banner entries so they can be directly added to the Household, instead of a Lance Force selection. There are several restrictions on banners when placed in a Lance which can not be enforced if these banners are not part of a Lance Force.

While I understand the confusion about how to create a Lance and add banners to it, imho this is not the correct way of addressing this issue.

**Comment by Prioress** [comment]
No stress if you want to discard the change, I’ve learned a LOT about
coding recently and I can easily see that this was not the best solution.
Plus I now have a lot more experience with git. My next pull will be a lot
more substantial. Probably. If this works in C I have not checked it since
I started learnint >_<

**Comment by MoDLegion** [comment]
Closing this now as per the comments here. The readme has been updated as part of #218 with instructions on how to building a household list works, which will hopefully about similar confusion in the future.

**Pull request closed without merging**
